STUDENT_INDEX:str = "196615"

MAIN_DIAGONAL_VALUE:int = 5 + int(STUDENT_INDEX[3])
SECOND_DIAGONAL_VALUE:int = -1
THIRD_DIAGONAL_VALUE:int = -1

MATRIX_SIZE:int = 1200 + 10 * int(STUDENT_INDEX[4]) + int(STUDENT_INDEX[5])

RESIDUAL_NORM:int = 1e-9